services:  
 # gameservice.api:  
 #   image: ${DOCKER_REGISTRY-}gameserviceapi:latest  
 #   build:  
 #     context: .  
 #     dockerfile: src/GameService/GameService.Api/Dockerfile  
 #   environment:  
 #     - ASPNETCORE_ENVIRONMENT=Development  
 #     - ASPNETCORE_HTTP_PORTS=8080  
 #     - ASPNETCORE_HTTPS_PORTS=8081  
 #     - ASPNETCORE_Kestrel__Certificates__Default__Password=YourPassword  
 #     - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx  
 #   ports:  
 #     - "8080:8080"
 #     - "8081:8081"
 #   volumes:  
 #     - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro  
 #     - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro  
 #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro  
 #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
 #   depends_on:
 #     - postgres
 #     - rabbitmq

 postgres:  
   image: postgres:latest  
   environment:  
     - POSTGRES_USER=sa  
     - POSTGRES_PASSWORD=sa  
     - POSTGRES_DB=GameNewsPlatform
   ports:  
     - "5432:5432"  #use host.docker.internal in pgadmin
   volumes:  
     - postgres_data:/var/lib/postgresql/data

 pgadmin:
  image: dpage/pgadmin4:latest
  environment:
    - PGADMIN_DEFAULT_EMAIL=sa@sa.sa
    - PGADMIN_DEFAULT_PASSWORD=sa
  ports:
    - "5050:80"
  volumes:
    - pgadmin_data:/var/lib/pgadmin
  depends_on:
    - postgres

 rabbitmq:
   image: rabbitmq:3-management
   ports:
     - "5672:5672"
     - "15672:15672"
   environment:
     - RABBITMQ_DEFAULT_USER=sa
     - RABBITMQ_DEFAULT_PASS=sa
   volumes:
     - rabbitmq_data:/var/lib/rabbitmq

volumes:  
 postgres_data:
 rabbitmq_data:
 pgadmin_data:   